misat:	SAT-alumnes.cpp
	g++ -O3 -Wall SAT-alumnes.cpp -o misat
misat_v1: SAT-alumnes-v1.cpp
	g++ -O3 -Wall SAT-alumnes-v1.cpp -o misat_v1
misat_v2: SAT-alumnes-v2.cpp
	g++ -O3 -Wall SAT-alumnes-v2.cpp -o misat_v2
misat_ANA: SAT-anabohueles.cpp
	g++ -O3 -Wall SAT-anabohueles.cpp -o misat_ANA
misat_raro: SAT-raro.cpp
	g++ -O3 -Wall SAT-raro.cpp -o misat_raro
misat_rarov2: SAT-rarov2.cpp
	g++ -O3 -Wall SAT-rarov2.cpp -o misat_rarov2
